services:
  - type: web
    name: paypal-download-integration
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PAYPAL_MODE
        value: sandbox
      - key: PAYPAL_CLIENT_ID
        value: AapqVwFYqt4Bjj5_7CoYTF0tUJH5pcqPa9KhdHMNHcGcQbZ9KlQEhTXEv8BYTxV94AYpDyORpT0vm_t9
      - key: PAYPAL_CLIENT_SECRET
        sync: false
      - key: ITEM_PRICE
        value: "5.00"
      - key: ITEM_CURRENCY
        value: USD
      - key: VAULT_SECRET_KEY
        generateValue: true
